services:
  - type: web
    name: c2s-backend
    runtime: python
    repo: https://github.com/votre-utilisateur/c2c-deploy
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: c2s-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 480
      - key: CORS_ORIGINS
        value: "*"

databases:
  - name: c2s-db
    databaseName: c2s
    plan: free
